version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "mypassword"
      POSTGRES_DB: "mydb"
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog_app
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USER: "myuser"
      DB_PASSWORD: "mypassword"
      DB_NAME: "mydb"
    ports:
      - "8081:8081"
    depends_on:
      - db

volumes:
  db_data:
